# Local environment (should point to the directory this repository was cloned into.)
BASE_DIR=/home/chrizzo/dev/knulli
TARGET=a133

# git settings
GIT_USER=chrizzo-hb
GIT_EMAIL=chrizzo@null.void # don't put your real email here unless you want spam

# device login
DEVICE_LOGIN=root@brick-cg

# Repository configuration for distribution and emulationstation, local directories configuration
# Note: URLs should point to YOUR FORKS of the respective repositories
DISTRIBUTION_FORK_REPO=https://github.com/chrizzo-hb/knulli-distribution
EMULATIONSTATION_FORK_REPO=https://github.com/chrizzo-hb/knulli-emulationstation
LOCAL_DISTRIBUTION_DIR_NAME=knulli-distribution
LOCAL_EMULATIONSTATION_DIR_NAME=knulli-emulationstation

# Project Information
# Note: the test branch suffix will be added to the end of feature branch name. I.E. 'quick_resume_mode' -> 'quick_resume_mode_testing'
FEATURE_BRANCH_NAME=emulationstation
TEST_BRANCH_SUFFIX=testing

# Generated branch names, change at your own risk
DISTRO_FORK_BRANCH=$FEATURE_BRANCH_NAME
DISTRO_FORK_TESTING_BRANCH=${FEATURE_BRANCH_NAME}_${TEST_BRANCH_SUFFIX}
ES_FORK_GIT_BRANCH=$FEATURE_BRANCH_NAME
ES_FORK_GIT_TESTING_BRANCH=${FEATURE_BRANCH_NAME}_${TEST_BRANCH_SUFFIX}
